version: '3.8'

services:
  # PostgreSQL service
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - app_network

  # Django service
  django-app:
    image: django-app
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

  # React service
  react-app:
    image: react-app
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
